---
resources:
  - name: pipeline-source-code
    type: git
    source: 
      uri: ((pipeline-repo))
      branch: main
      private_key: ((private-key))
  - name: testotester-source-code
    type: git
    source:
      uri: ((testotester-repo))
      branch: main
      private_key: ((private-key))

jobs:
  - name: build-app
    serial: true
    public: true
    plan:
      - get: pipeline-source-code
      - get: testotester-source-code
      - task: setup-environment
        params:
          CF_API: ((cf-api))
          CF_ORG: ((cf-org))
          CF_SPACE: ((cf-space))
          CF_USER: ((cf-username))
          CF_PASS: ((cf-password))
        file: pipeline-source-code/tasks/setup-environment.yml
      - task: create-build
        file: pipeline-source-code/tasks/create-build.yml
      
