---
platform: linux
image_resource:
  type: docker-image
  source: {repository: starkandwayne/concourse}

inputs:
  - name: testotester-source-code
  - name: pipeline-source-code

outputs:
  - name: app-build
  
run:
  path: pipeline-source-code/scripts/create-java-build.sh