---
platform: linux
image_resource:
  type: docker-image
  source: {repository: starkandwayne/concourse}

inputs:
  - name: app-build
  - name: pipeline-source-code
  
run:
  path: pipeline-source-code/scripts/deploy-app.sh